<h1>Импорт библиотек

In [3]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [28]:
import numpy as np

def sum_prod(X, V):
    return np.sum([X[i].dot(V[i]) for i in range(len(X))], axis=0)

def test_sum_prod():
    test_cases = [
        (
            [  
                np.matrix([[1, 2], [3, 4]]),
                np.matrix([[5, 6], [7, 8]])
            ],
            [  
                np.array([1, 1]),
                np.array([2, 2])
            ],
            np.array([25, 37])
        ),
        (
            [  
                np.matrix([[-1, -2, -3], [-4, -5, -6], [-7, -8, -9]]),
                np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
            ],
            [  
                np.array([1, 0, -1]),
                np.array([1, 1, 1])
            ],
            np.array([8, 17, 26]) 
        ),
    ]

    for matrix, vectors, expected in test_cases:
        result = sum_prod(matrix, vectors)
        print(f"Matrix:\n{np.array(matrix)}\nVectors:\n{np.array(vectors)}")
        assert np.allclose(result, expected), \
            f"Test failed: expected {expected}, got {result}"
        print(f"Test passed: expected {expected}, got {result}\n")

    print("All tests completed.")

test_sum_prod()


Matrix:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Vectors:
[[1 1]
 [2 2]]
Test passed: expected [25 37], got [[25 37]]

Matrix:
[[[-1 -2 -3]
  [-4 -5 -6]
  [-7 -8 -9]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
Vectors:
[[ 1  0 -1]
 [ 1  1  1]]
Test passed: expected [ 8 17 26], got [[ 8 17 26]]

All tests completed.


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [36]:
import numpy as np

def binarize(M, threshold=0.5):
    return (M > threshold).astype(int)

def test_binarize():
    matrix = np.matrix([[-2,-1,0], [1,2,3], [4,5,6]])
    test_cases = [
        (0, np.matrix([[0, 0, 0], [1, 1, 1], [1, 1, 1]])),
        (-1, np.matrix([[0, 0, 1], [1, 1, 1], [1, 1, 1]])), 
        (2, np.matrix([[0, 0, 0], [0, 0, 1], [1, 1, 1]]))  
    ]
    
    print("For test matrix:")
    print(matrix)
    for threshold, expected in test_cases:
        result = binarize(matrix, threshold)
        assert np.allclose(result, expected), \
            f"Test failed for threshold = {threshold}: expected \n{np.array(expected)}, \nresult \n{np.array(result)}"
        print(f"Test passed for threshold = {threshold}: expected \n{np.array(expected)}, \nresult\n{np.array(result)}")
    print("All tests completed.")

test_binarize()

For test matrix:
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
Test passed for threshold = 0: expected 
[[0 0 0]
 [1 1 1]
 [1 1 1]], 
result
[[0 0 0]
 [1 1 1]
 [1 1 1]]
Test passed for threshold = -1: expected 
[[0 0 1]
 [1 1 1]
 [1 1 1]], 
result
[[0 0 1]
 [1 1 1]
 [1 1 1]]
Test passed for threshold = 2: expected 
[[0 0 0]
 [0 0 1]
 [1 1 1]], 
result
[[0 0 0]
 [0 0 1]
 [1 1 1]]
All tests completed.


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [ ]:
def unique_rows(mat):
    # Your code goes here
    pass

def unique_columns(mat):
    # Your code goes here
    pass

<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
# Your code goes here

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [ ]:
def chess(m, n, a, b):
    # Your code goes here
    pass

<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [1]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
# Your code goes here